import keyMirror from 'keymirror'

export default keyMirror({
  // app actions
  INIT_APP: null,
  RESET_APP: null,
  INCREMENT_COUNTER: null,
  TOGGLE_TRANSITIONS: null,
  LOAD_DATA: null,
  // Constants Data 
  DATAFIRST: null, 
  DROPDOWN_PAGES: null,
  REGIONSOFPAGE: null,  
  HEADER_USER_SECTIONS: null,
  FOOTER_USER_SECTIONS: null,
  SECTION_FIELDS: null,
  UPDATE_SECTION_FIELDS: null,
  NEW_VAL_FIELDS: null,
  TO_SAVE_FIELDS: null,
  LOOK_UP_KEY: null,
  SEARCH_CATE: null,
  SEARCH_PRO: null,
  SEARCH_LINK: null,
  LINK_INPUT_VAlUE: null,
  GET_LANGS: null,  
  TEMPLATE_SETTING: null,
  Add_New_Section: null,
  INSERT_SECTION: null,
  LAYOUTS_PAGES: null,
  ADD_LAYOUT: null,
  CLOSE_ADD_PAGE: null,  
  SEARCH_BRANDS: null,
  SET_LANG: null,
  NOTIFICATION: null,
  TOGGEL_SECTION: null,
  ROUTE_COMPONENT: null,
  SECTION_ID: null,
  Back_ROUTE_COMPONENT: null, 
  WEB_PAGES: null,
  TEMPLATE_INFO: null,
  USER_CURRENTPLAN: null
})
