import LocalizedStrings from 'react-localization';

const translationStrings = new LocalizedStrings({
    en: {
        Browse: "Browse",
        Clear: "Clear", 
        HomePage: 'home page',
        AddNewSection: 'Add New Section',
        Lang: 'عربي',
        Reset: 'Reset',
        Publish:"Publish",
        SectionsAvailable: 'sections Available',
        MainTheme: 'Main Theme',
        MessagePopup: "Missing updates",
        PargPopup : "If you haven't published them, you will miss out on the updates you made, before returning to the dashboard Are you sure you want to return to the dashboard?        ",
        Cancel: 'Cancel',
        Confirm: "Confirm",
        MessageResetPopup: 'Reset Template to Default',
        PargResetPopup: 'Resetting the template to default, will rollback all the template settings, design settings, layouts, slides, and banners to its default state. This action is not reversible.Are you sure you want to reset the template to default?',
        btnResetpopup: "Reset to Default",
        SaveMessage: "The Changes Fields Saved Successfully",
        SaveMessageTitle: 'Save Fields',
        PublishMessage: "Publish Data Is Successfully",
        SectionNotFound : "No Section Found",
        ConfirmMsgForDeleteSection : 'Are you sure you want to delete this section ?',
        TitleDeleteSection:"Delete Section",
        internalPages: "Internal Pages",
        Exiteditor: "Exit editor",
        Delete_modal: 'Delete',
        save:"save",
        mainLayout:"main Layout",
        notChanged:"Please Change Any Fields Value",
        OldEditor: 'Switch to old editor',
        Select: 'select'
    },
    ar: {
        Browse: "تحميل",
        Clear: "مسح",
        HomePage: 'الصفحة الرئيسية',
        AddNewSection: 'إضافة قسم جديد',
        Lang: 'EN',
        Reset: 'إعادة تعيين',
        Publish:'نشر التحديثات',
        SectionsAvailable: 'الأقسام المتاحة',
        MainTheme: 'الثيمات الرئيسية',
        MessagePopup: "فقدان التحديثات",
        PargPopup : `سوف تفقد التحديثات التى قمت بها إذا لم تقم بنشرها، قبل العودة للوحة التحكم
هل أنت متأكد أنك تريد العودة للوحة القيادة؟`,
        Confirm:"تأكيد",
        Cancel: 'إلغاء',
        MessageResetPopup: 'إعادة تعيين القالب إلى الافتراضي',
        PargResetPopup: 'ستؤدي إعادة تعيين القالب إلى الوضع الافتراضي إلى التراجع عن جميع إعدادات القالب وإعدادات التصميم والتخطيطات والشرائح واللافتات إلى حالتها الافتراضية. هذا الإجراء غير قابل للعكس. هل أنت متأكد أنك تريد إعادة تعيين القالب إلى الافتراضي؟ ',
        btnResetpopup: "إعادة تعيين إلى الافتراضي",
        SaveMessage: "تم حفظ التغييرات الحقول بنجاح",
        SaveMessageTitle: 'حفظ الحقول',
        PublishMessage: "نشر البيانات بنجاح",
        SectionNotFound : "لم يتم العثور على قسم",
        ConfirmMsgForDeleteSection : 'هل أنت متأكد أنك تريد حذف هذا القسم؟',
        Delete_modal: 'حذف',
        TitleDeleteSection:"حذف القسم",
        internalPages: "الصفحات الداخلية",
        Exiteditor: "الخروج من المحرر",
        save:"حفظ",
        mainLayout:"نموذج الرئيسي",
        notChanged:"الرجاء تغيير أي قيمة في الحقول",
        OldEditor: ' العودة الى المحرر القديم',
        Select: 'اختار'
    }
});
export default translationStrings;